### ISSUE TITLE
SSL:Session class properties not applied to BearSSL Client Connection yet

### ISSUE THREAD

**Issue by kpishere** [mikee47/Sming#7]
@mikee47 If I'm understanding correctly, it looks like you're on the edge of doing this ... as you've said already.

Where properties are set and being passed around in Ssl:Session class, I'm expecting that they are applied in this method 

int BrClientConnection::init()

but currently only default SSL settings are applied there.

If I helped with this, would that be useful or would I just be getting in your way?

**Comment by kpishere** [comment]
So, just tooling around bit with this to understand/confirm.  After checking BearSSL docs, it appears you set the buffer size smaller then 16K (generally) and it will add the extension to negotiate the smaller block size.

In file ssl/BearSsl/BrConnection.h I did " / 4" to make roughly 4K buffer : 

private:
        br_ssl_client_context clientContext;
        uint8_t buffer[BR_SSL_BUFSIZE_MONO **/ 4**];
        X509Context* x509Context = nullptr;
        mutable BrCertificate* certificate = nullptr;
        bool handshakeDone = false;


And sure enough, in this pic, you see it does do it.

max_frag
![max_frag](https://user-images.githubusercontent.com/25204173/71503974-73455700-2845-11ea-97ca-a0ea8d52deae.png)

But, use if this extension is 'broken' and not consistently supported across implementations.  there is a new extension to replace this one, [record size](https://tools.ietf.org/id/draft-ietf-tls-record-limit-01.html) -- it too is very new but looks to be the way forward when more widely supported.

Anyhow, for the Microsoft service, they don't support the max_fragment one and I got this : 

https://login.microsoftonline.com/e500d90a-f722-4c6b-a5b8-6fda28cef811/oauth2/v2.0/authorize?scope=offline_access+openid+profile+calendars.read&response_type=code&client_id=7b1ee9f0-3786-4ed0-967d-06822d91b972&redirect_url=http%3a//192.168.2.2%3a80&response_mode=query
96499078 SSL CLOSED, last error = 6 (TOO_LARGE), heap free = 22576

**Comment by mikee47** [comment]
We need a more flexible mechanism for applications to configure all this stuff. At present we have a few items stored within an HttpRequest: `sslOptions`, `sslFingerprints` and `sslKeyCertPair`. A better way I think would be to replace those with a single callback delgate, something like this:

`using SslInitDelegate = Delegate<void(Ssl::Session& session, void* param)>`.

Applications then set:

`request->onSslInit(mySslInitCallback, &request)`.

Or something similar. Thoughts?
